# Generated by Django 4.2.1 on 2023-07-01 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_category_options_listing_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
