# Generated by Django 4.2.1 on 2023-07-04 13:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_commented',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
