# Generated by Django 4.2.1 on 2023-09-19 09:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0015_watchlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="watch_listed",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="watch_listed_by",
        ),
    ]
